--------------------------------------------------------
--  File created - Saturday-September-04-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAGE
--------------------------------------------------------

  CREATE TABLE "WASSIM"."CAGE" 
   (	"ID_CAGE" VARCHAR2(20 BYTE), 
	"TYPE_CAGE" VARCHAR2(20 BYTE), 
	"CAPACITE_CAGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ANIMAL
--------------------------------------------------------

  CREATE TABLE "WASSIM"."ANIMAL" 
   (	"ID_ANIMAL" VARCHAR2(20 BYTE), 
	"NOM_ANIMAL" VARCHAR2(20 BYTE), 
	"SEXE_ANIMAL" VARCHAR2(20 BYTE), 
	"DATE_NAISSANCE" VARCHAR2(20 BYTE), 
	"DATE_DECES" VARCHAR2(20 BYTE), 
	"ID_CAGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into WASSIM.CAGE
SET DEFINE OFF;
Insert into WASSIM.CAGE (ID_CAGE,TYPE_CAGE,CAPACITE_CAGE) values ('9','Sauvage','1');
Insert into WASSIM.CAGE (ID_CAGE,TYPE_CAGE,CAPACITE_CAGE) values ('7','Aquatique','10');
Insert into WASSIM.CAGE (ID_CAGE,TYPE_CAGE,CAPACITE_CAGE) values ('4','Aquatique','5');
Insert into WASSIM.CAGE (ID_CAGE,TYPE_CAGE,CAPACITE_CAGE) values ('8','Sauvage','2');
Insert into WASSIM.CAGE (ID_CAGE,TYPE_CAGE,CAPACITE_CAGE) values ('10','Sauvage','8');
Insert into WASSIM.CAGE (ID_CAGE,TYPE_CAGE,CAPACITE_CAGE) values ('11','Amphibie','5');
Insert into WASSIM.CAGE (ID_CAGE,TYPE_CAGE,CAPACITE_CAGE) values ('12','Amphibie','15');
REM INSERTING into WASSIM.ANIMAL
SET DEFINE OFF;
Insert into WASSIM.ANIMAL (ID_ANIMAL,NOM_ANIMAL,SEXE_ANIMAL,DATE_NAISSANCE,DATE_DECES,ID_CAGE) values ('1','Rockie','male','10/06/2009','1/1/1900','6');
Insert into WASSIM.ANIMAL (ID_ANIMAL,NOM_ANIMAL,SEXE_ANIMAL,DATE_NAISSANCE,DATE_DECES,ID_CAGE) values ('2','Rex','female','2/1/2022','1/1/1900','6');
Insert into WASSIM.ANIMAL (ID_ANIMAL,NOM_ANIMAL,SEXE_ANIMAL,DATE_NAISSANCE,DATE_DECES,ID_CAGE) values ('3','Minoucha','female','10/9/2021','12/09/2022','1');
Insert into WASSIM.ANIMAL (ID_ANIMAL,NOM_ANIMAL,SEXE_ANIMAL,DATE_NAISSANCE,DATE_DECES,ID_CAGE) values ('4','Aeib','male','23/05/2017','1/1/1900','1');
Insert into WASSIM.ANIMAL (ID_ANIMAL,NOM_ANIMAL,SEXE_ANIMAL,DATE_NAISSANCE,DATE_DECES,ID_CAGE) values ('5','Mila','female','08/03/2020','1/1/1900','6');
--------------------------------------------------------
--  DDL for Index CAGE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."CAGE_PK" ON "WASSIM"."CAGE" ("ID_CAGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ANIMAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WASSIM"."ANIMAL_PK" ON "WASSIM"."ANIMAL" ("ID_ANIMAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger CAGE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASSIM"."CAGE_TRG" 
BEFORE INSERT ON CAGE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CAGE IS NULL THEN
      SELECT CAGE_SEQ.NEXTVAL INTO :NEW.ID_CAGE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASSIM"."CAGE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ANIMAL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "WASSIM"."ANIMAL_TRG" 
BEFORE INSERT ON ANIMAL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ANIMAL IS NULL THEN
      SELECT ANIMAL_SEQ.NEXTVAL INTO :NEW.ID_ANIMAL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "WASSIM"."ANIMAL_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table CAGE
--------------------------------------------------------

  ALTER TABLE "WASSIM"."CAGE" ADD CONSTRAINT "CAGE_PK" PRIMARY KEY ("ID_CAGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASSIM"."CAGE" MODIFY ("ID_CAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ANIMAL
--------------------------------------------------------

  ALTER TABLE "WASSIM"."ANIMAL" ADD CONSTRAINT "ANIMAL_PK" PRIMARY KEY ("ID_ANIMAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "WASSIM"."ANIMAL" MODIFY ("ID_ANIMAL" NOT NULL ENABLE);
